name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_WATER_088E4AF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          ## Move these to Github secrets and replace values with e.g
          # REACT_APP_COLUMNS_PER_PAGE: ${{ secrets.REACT_APP_COLUMNS_PER_PAGE }}
          # REACT_APP_DAY_START_HOUR: ${{ secrets.REACT_APP_DAY_START_HOUR }}
          # REACT_APP_DAY_END_HOUR: ${{ secrets.REACT_APP_DAY_END_HOUR }}
          # REACT_APP_REFRESH_INTERVAL_MINUTES: ${{ secrets.REACT_APP_REFRESH_INTERVAL_MINUTES }}
          # REACT_APP_CLASSROOMS_API_URL: ${{ secrets.REACT_APP_CLASSROOMS_API_URL }}
          # REACT_APP_AVAILABILITY_API_URL: ${{ secrets.REACT_APP_AVAILABILITY_API_URL }}
          ##
          REACT_APP_COLUMNS_PER_PAGE: "10"
          REACT_APP_DAY_START_HOUR: "7"
          REACT_APP_DAY_END_HOUR: "18"
          REACT_APP_REFRESH_INTERVAL_MINUTES: "5"
          REACT_APP_CLASSROOMS_API_URL: "https://classroomview-func.azurewebsites.net/api/getClassrooms?code=EHMKiWVC0m_G_mZsU0wdadDL7bu9_D-73n0ha8X1zlTBAzFuM-HO3g%3D%3D"
          REACT_APP_AVAILABILITY_API_URL: "https://classroomview-func.azurewebsites.net/api/getCalendarData?code=uqs8Zf76n5EcLAQ4qosrD2WJ5NOPxEMf-WGZo2U3LPoCAzFuEbIsVQ%3D%3D"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_WATER_088E4AF03 }}
          action: "close"
          app_location: "/"
